sudo: required
language: node_js
node_js:
  - "7.7.1"

services:
  - docker

before_install:
    - docker build .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKERHUB_ORG/asheron.net:latest;
    fi
